Matrix multiplier
Niksen111/spbuHomeworksSem3 pull request #1
Opened 2022-09-20 11:54 UTC by Niksen111

Library representing the parallel multiplication of matrices

2022-12-03 15:07 UTC, yurii-litvinov requested changes

2022-12-03 15:07 UTC, yurii-litvinov commented on 1Homework07.09.22/ParallelMatrixMultiplication/ParallelMatrixMultiplication/NonRepeatableMatricesException.cs
> +public class NonRepeatableMatricesException : Exception
Надо комментарии

2023-02-09 18:14 UTC, Niksen111 commented on 1Homework07.09.22/ParallelMatrixMultiplication/ParallelMatrixMultiplication/MatrixMultiplier.cs
> +            _threads[i] = new Thread(() =>
Задумка была в том, чтобы один раз создавались потоки в статическом классе, и потом можно было бы им давать матрицы на перемножение (пул потоков только для перемножение матриц).

2023-02-10 11:58 UTC, yurii-litvinov approved these changes
👍

2023-02-10 11:58 UTC, yurii-litvinov commented on 1Homework07.09.22/ParallelMatrixMultiplication/Matrix/Matrix.cs
> +    }
Можно было бы более активно использовать синтаксис с `=>` (даже в конструкторах)

2023-02-10 14:12 UTC, merged